# Generated by Django 5.1.4 on 2025-01-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="recipient",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Получатель уведомления",
            ),
        ),
    ]
