# Generated by Django 5.1.4 on 2025-01-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notificationlog_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True,
                help_text="Время отправки с учетом задержки, заполняется автоматически",
                null=True,
                verbose_name="Время отправки",
            ),
        ),
    ]
